#!/bin/bash
###################
#deploy docker container
###################

branch=$1
cloud_short_name=$2
port=$3
cloud_name="mamahao-ebiz-"${cloud_short_name}
web_cloud_name="mamahao-${cloud_short_name}-web"
if [[ ${cloud_short_name} = "api" ]]; then
  cloud_name="mamahao-app-api"
  web_cloud_name="mamahao-app-web"
fi

cd /code/${branch}/${cloud_name}

printf "the path: %s\n" $PWD

##############clean package cloud application###################

mvn clean package -DskipTests=true

##############mkdir docker file ###################

dockerfile_dir="/dockerfiles/"${cloud_short_name}

printf "mkdir docker file %s\n" ${dockerfile_dir}

if [ ! -d ${dockerfile_dir} ];then
  mkdir ${dockerfile_dir}
fi

cd ${dockerfile_dir}

dockerfile=${dockerfile_dir}"/dockerfile"

if [ ! -f ${dockerfile} ];then
  touch "${dockerfile}"
  echo "FROM hub.c.163.com/library/java:8">>"${dockerfile}"
  echo "MAINTAINER ${cloud_name}">>"${dockerfile}"
  echo "COPY ${web_cloud_name}.jar /${cloud_short_name}.jar">>"${dockerfile}"
  echo "CMD java -jar /${cloud_short_name}.jar">>"${dockerfile}"
  echo "EXPOSE ${port}">>"${dockerfile}"
  debugPort=`expr ${port} + 1000`
  echo "EXPOSE ${debugPort}">>"${dockerfile}"
  # echo "CMD [\"java\",\"-jar\",\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${debugPort}\",\"-Dspring.profiles.active=test\",\"${cloud_short_name}.jar\"]"
  echo "CMD [\"java\",\"-jar\",\"-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=${debugPort}\",\"${cloud_short_name}.jar\"]">>"${dockerfile}"
fi

cat ${dockerfile}

time=$(date "+%Y%m%d-%H%M%S")

##############backup jar ###################
mv ${web_cloud_name}.jar ${web_cloud_name}-${time}.jar

##############delete other container and images ###################
docker ps -a | grep -E "Exited|Created|${cloud_name}|${port}" | awk '{print $1}' | xargs docker stop
docker ps -a | grep -E "Exited|Created|${cloud_name}|${port}" | awk '{print $1}' | xargs docker rm
docker images | grep -E "none|${cloud_short_name}" | awk '{print $3}'| xargs docker rmi

code_path="/code/${branch}/${cloud_name}/${web_cloud_name}"
cp ${code_path}/target/${web_cloud_name}.jar ${web_cloud_name}.jar

docker build -t ${cloud_name} .

##############run cloud docker ###################

docker run -d -p ${port}:${port} ${cloud_name}

docker ps -a

printf "#################################################"

application_path="${code_path}/src/main/resources"
cat ${application_path}/application.yml
printf "\n"
printf "#################################################"

cat ${application_path}/application-dev.yml
printf "\n"
printf "#################################################"

cat ${application_path}/application-test.yml
printf "\n"

sleep 5

exit

