#!/bin/bash
###################
# tail docker log
#################

cloud_name=$1
tail_line=$2

if [[ ! $tail_line ]]; then
   tail_line=50
fi

printf "the cloud_name %s, the tail_line %s\n" $cloud_name $tail_line

c_id=`docker ps -a | grep -E "${cloud_name}" | grep -E "Up" | awk '{print $1}'`

printf "the container id %s\n" $c_id

if [[ ! $c_id ]]; then
   m_id=`docker images | grep -E "${cloud_name}" | awk '{print $3}'`
   if [[ ! $m_id ]]; then
      printf "the container not exist\n"
      exit 1
   fi
   printf "the image id %s\n" $m_id
   c_id=`docker ps -a | grep -E "${m_id}" | grep -E "Up" | awk '{print $1}'`
   printf "the container id %s\n" $c_id
fi

if [[ ! $c_id || $c_id = "CONTAINER" ]]; then
   printf "the container not exist\n"
   exit 1
fi

printf "the container id %s\n" $c_id

docker logs -f -t --tail $tail_line $c_id



